version: '3.1'

services:
  server:
    build: './server/'
    environment:
      PG_HOST: db
      DEBUG: express:*
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
  client:
    build: './client'
    environment:
      REACT_APP_API_URL: localhost:3001/api
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - datadb:/var/lib/postgresql/data
volumes:
  datadb:
    driver: local
