version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local